# Generated by Django 5.2.5 on 2025-08-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiveNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2000)),
                ('publication_date', models.DateTimeField()),
                ('news_category', models.CharField(max_length=200)),
                ('prediction', models.BooleanField(default=True)),
                ('section_id', models.CharField(max_length=200)),
                ('section_name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('web_url', models.CharField(max_length=600)),
                ('img_url', models.CharField(max_length=600)),
            ],
        ),
    ]
