# Generated by Django 4.2.3 on 2025-08-22 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Livenews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('correct', 'Correct Prediction'), ('incorrect', 'Incorrect Prediction'), ('unsure', 'Not Sure')], max_length=20)),
                ('user_comment', models.TextField(blank=True, help_text='Optional comment from user', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='Livenews.livenews')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'news')},
            },
        ),
    ]
